options {
    listen-on port 53 { 127.0.0.1; };
    listen-on-v6 port 53 { ::1; };
    directory "/var/named";
    dump-file "/var/cache/bind/stats/dump.db";
    statistics-file "/var/cache/bind/stats/named.txt";
    memstatistics-file "/var/cache/bind/stats/mem.txt";
    recursing-file "/var/cache/bind/data/recursing";
    secroots-file "/var/cache/bind/data/secroots";
    allow-query { localhost; };
    allow-query-cache { localhost; };
    recursion yes;
    dnssec-enable yes;
    dnssec-validation yes;
    dnssec-lookaside auto;
    bindkeys-file "/etc/bind/iscdlv.key";
    managed-keys-directory "/var/cache/bind/dynamic";
    pid-file "/run/named/named.pid";
    session-keyfile "/run/named/session.key";
};

logging {
  channel default_debug {
      file "data/named.run";
      severity dynamic;
  };
};

zone "." IN {
    type hint;
    file "named.ca";
};

include "/etc/bind/rfc1912.zone";
include "/etc/bind/root.key";
