[backup]
  path = /mnt/backups
  comment = backups
  uid = root
  gid = root
  read only = yes
  list = yes
  hosts allow = 127.0.0.1 ::1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 fc00::/7
  hosts deny = *
