APT::Get::Assume-Yes "true";
APT::Get::AllowUnauthenticated "false";
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
Acquire::Retries "3";
Acquire::http::Timeout "30";
Acquire::ForceIPv4 "true";
