# Default nginx configuration
proxy_intercept_errors off;

  location = /favicon.ico {
    log_not_found off;
        access_log off;
    }

  location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

  location /.well-known {
        alias /var/www/html/.well-known;
    }

  location ^~ /html/ {
        alias /usr/local/share/httpd/default-html/;
        try_files $uri $uri/ =403;
    }

  location ^~ /default-html/ {
        alias /usr/local/share/httpd/default-html/;
        try_files $uri $uri/ =403;
    }

  location ^~ /default-js/ {
        alias /usr/local/share/httpd/default-js/;
        try_files $uri $uri/ =403;
    }

  location ^~ /js/ {
        alias /usr/local/share/httpd/default-js/;
        try_files $uri $uri/ =403;
    }

  location ^~ /css/ {
        alias /usr/local/share/httpd/default-css/;
        try_files $uri $uri/ =403;
    }

  location ^~ /default-css/ {
        alias /usr/local/share/httpd/default-css/;
        try_files $uri $uri/ =403;
    }

  location ^~ /icons/ {
        alias /usr/local/share/httpd/default-icons/;
        try_files $uri $uri/ =403;
    }

  location ^~ /default-icons/ {
        alias /usr/local/share/httpd/default-icons/;
        try_files $uri $uri/ =403;
    }

# error pages
  location ^~ /default-error/ {
        add_header Cache-Control no-cache;
        alias /usr/local/share/httpd/default-error/;
        autoindex off;
        autoindex_exact_size off;
        autoindex_format html;
        autoindex_localtime on;
        try_files $uri =503;
    }

  location ^~ /healthz/ {
        alias /usr/local/share/httpd/default-health/;
        try_files $uri $uri/ =403;
    }

  location ^~ /default-health/ {
        alias /usr/local/share/httpd/default-health/;
        try_files $uri $uri/ =403;
    }

  location /health/nginx {
        stub_status;
    }

  error_page 403 /default-error/403.html;
  error_page 404 /default-error/404.html;
  error_page 500 /default-error/500.html;
  error_page 502 /default-error/502.html;
  error_page 503 /default-error/503.html;
  error_page 504 /default-error/504.html;

# security headers
  add_header X-Frame-Options           "SAMEORIGIN" always;
  add_header X-XSS-Protection          "1; mode=block" always;
  add_header X-Content-Type-Options    "nosniff" always;
  add_header Referrer-Policy           "no-referrer-when-downgrade" always;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header Content-Security-Policy   "script-src 'self' 'unsafe-inline' 'unsafe-eval' *; frame-src 'self' *; object-src 'self'" always;
